### ISSUE TITLE
xmlns attribute

### ISSUE THREAD

**Issue by ideogram** [evtn/soda#17]
Should an SVG file have a `xmlns="http://www.w3.org/2000/svg"` declaration in the root?

(Without it, Gapplin and PyCharm warn me the file is invalid and won't display it. Illustrator and InkScape render it happily, though.)

If so, should Soda somehow support the inclusion of it? Something like:

from:
```
        root = Root(
            viewBox="-400 -400 800 800",
            xmlns="http://www.w3.org/2000/svg"
        )
```

to:
```
        root = Root(
            viewBox="-400 -400 800 800",
            namespace = True
        )
```

(My apologies if this doesn't make sense. And thanks for the very practical library!)

**Comment by evtn** [comment]
It depends on where you open it, the rule of thumb is to include the namespace if you are not sure.

I think I've missed it in docs, but `Root` has `use_namespace` parameter:

```python
from soda import Root

print(Root(use_namespace=True))
# <svg version="2.0" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"></svg>
```

Will add it to the docs sometimes soon

**Comment by ideogram** [comment]
Thank you. Indeed, `Root` has the `use_namespace` parameter. It's right there, in `__init__` I've no idea why I missed it.
