### ISSUE TITLE
Path().build() default separator causes invalid path

### ISSUE THREAD

**Issue by gnbl** [evtn/soda#2]
Path.build() uses a comma `,` as default separator between commands, which apparently is invalid - at least Firefox does not render the resulting path, and https://svg-path-visualizer.netlify.app/ prints "Unexpected character "A" at index 9. Command cannot follow comma".

    M 10 30, A 20 20 0 0 1 50 30, A 20 20 0 0 1 50 30, Q 90 60 50 90, Q 10 60 10 30, Z

from

https://github.com/evtn/soda/blob/lord/README.md?plain=1#L227

**Comment by evtn** [comment]
Fixed in v0.1.8 (removed `sep` altogether, now " " is the only possible command separator in non-compact mode)

**Comment by gnbl** [comment]
That's not backwards compatible / breaks code using sep. I don't mind since that's only one line for me to change and I've just started using this lib.

**Comment by evtn** [comment]
It kinda isn't backward-compatible, sure.
But as "," is invalid and the only other option is " ", there is no reason to leave `sep` there.
Also, as version is `0.x.y`, [public API should not be considered stable](https://semver.org/#spec-item-4).

Although, maybe I should bump version to `1.x.y` as module is pretty much complete.
