### ISSUE TITLE
`class` attribute cannot be set

### ISSUE THREAD

**Issue by gnbl** [evtn/soda#4]
because it's a Python keyword...

**Comment by evtn** [comment]
You can use `Tag.whatever(..., **{"class": value})` as a workaround
If you have a more elegant proposal, I would be happy to hear it

**Comment by eolme** [comment]
I was very disappointed when I found out you can't assign a class, my sadness is overwhelming, my mental state is terrible, I can't sleep at night thinking about how sad it makes me to know you can't assign a class. It's unbearably hard, but we're with you and always ready to support you in this difficult time.

**Comment by eolme** [comment]
But you can choose either:
- clazz (java style)
- className (js style)
- _class (mongodb style)
- $class (php style)

**Comment by evtn** [comment]
Also, if you don't mind an extra statement, you can write

```python
tag = Tag.whatever(...)
tag["class"] = value
```

**Comment by gnbl** [comment]
Maybe add a named parameter "attributes" that holds a dict (or is a dict view) of the attributes, so `attributes = {"class": value}` - generic but verbose. Perhaps an unnamed dict parameter (`..., {"class": value}, ...)` could be used to specify attributes?
JavaScript DOM API tag elements have a `classList` property. `classes = []` or `classes=""`` But I haven't checked whether other keywords are conflicting.

**Comment by evtn** [comment]
Right now Tag constructor signature is

```python
def __init__(
    self,
    tag_name: str,
    *children: Node,
    self_closing: bool = True,
    **attributes: Value,
):
```
So there is a parameter called `attributes` which holds all named arguments (`**{"class": value}` workaround works on top of that).

I'm unsure about unnamed dictionary parameter (although I considered that) because it would go to `children` and it would require some additional checks on that parameter.

`classes` proposal makes sense, but while soda is aimed at SVG, I aim to support arbitrary XML generation and as such I don't want to add some SVG-specific conversions of parameters.

Right now you can use something like this:

```python
from soda import Tag

def set_class(self, *classes):
    return self(**{"class": " ".join(classes)})

Tag.set_class = set_class

tag = Tag.whatever(...).set_class("some_class", "another_class")
```

You can create a PR with this (or I would maybe add it myself in a few days)

**Comment by gnbl** [comment]
`tag = Tag.whatever(...).set_class("some_class", "another_class")`
keeps the one-line instantiation but isn't it HTML/SVG/class-attribute specific? So maybe

```
def set_attr(self, attribute, *classes):
    return self(**{attribute: " ".join(classes)})
```
To add to the confusion with another option:

 - expand on the `# '_' to '-' conversion` with `class_= ...`

**Comment by evtn** [comment]
> `tag = Tag.whatever(...).set_class("some_class", "another_class")` keeps the one-line instantiation but isn't it HTML/SVG/class-attribute specific? So maybe
> 
> ```python
> def set_attr(self, attribute, *classes):
>     return self(**{attribute: " ".join(classes)})
> ```

I think a more appropriate version of `set_attr` could look like that:

```python
def set_attr(self, attribute: str, value: Value) -> "Tag":
    self[attribute] = value
    return self
```

> To add to the confusion with another option:
> 
>     * expand on the `# '_' to '-' conversion` with `class_= ...`

Honestly, I got a bit confused by this part, could you please explain?

**Comment by gnbl** [comment]
You are converting underscores in attribute names into hyphens, e.g. `clip_path` becomes `clip-path`.
Similarly, removing a trailing underscore from an attribute name should allow quick typing while avoiding keyword collisions, e.g. `class_` becomes `class`.

**Comment by evtn** [comment]
I totally forgot about [`Tag.set_attribute`](https://github.com/evtn/soda/blob/ba5a99d766cee6bea4dfb6014c5fef724a7105f1/soda/tags.py#L77) method which already does roughly what proposed `set_attr` should do

I will consider '_' stripping but for now you can already use

`tag = Tag.whatever(...).set_attribute("class", "some_class")`

**Comment by gnbl** [comment]
Also consider namespaces, e.g. Inkscape needs obsolete `<use xlink:href=""/>`...

**Comment by evtn** [comment]
I guess it could be done with set_attribute, or with `**{"xlink:href": "your_link_here"}`

**Comment by evtn** [comment]
Starting with [1.1.0](https://github.com/evtn/soda/releases/tag/1.1.0), [leading and trailing underscores are removed by default](https://github.com/evtn/soda#attribute-conversion)
