### ISSUE TITLE
How to create attributes with hyphens in it?

### ISSUE THREAD

**Issue by dakoller** [evtn/soda#7]
I try to create text boxes and would like to specify svg attributes with hypens in them (like "font-size" or "stroke-width")
Unfortunately e.g. font-size is no valid python name for a function parameter. 

How would I do this in Python without construtcing to unescaped text?

**Comment by evtn** [comment]
This feature has a little documentation, but you actually can use `font_size` and `stroke_width` and the module would replace underscores with hyphens

**Comment by dakoller** [comment]
Great, thank you!
